#!/usr/bin/env bash
#This script displays the content of the current directory in list format
for file in *; do
    if [[ -f "$file" && ! "$file" =~ ^\. ]]; then
        # Extract the part after the first dash
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
